"""
Generate the rule catalogue (rule -> MITRE ATT&CK mapping) from the real Sigma
rules, so documentation can never drift from the code.

Writes docs/rule-catalogue.md and refreshes the table embedded in README.md
between the <!-- RULES:START --> / <!-- RULES:END --> markers.

Usage:
    python pipeline/rule_catalogue.py           # regenerate files
    python pipeline/rule_catalogue.py --check   # exit 1 if files are stale (CI)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
RULES_DIR = ROOT / "rules" / "sigma"
FIXTURES_DIR = ROOT / "tests" / "fixtures" / "sample_logs_malicious"
CATALOGUE = ROOT / "docs" / "rule-catalogue.md"
README = ROOT / "README.md"
START, END = "<!-- RULES:START -->", "<!-- RULES:END -->"

_TECH_RE = re.compile(r"^attack\.(t\d{4})(?:\.(\d{3}))?$")
_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "informational": 4}


def _logsource(ls: dict) -> str:
    parts = [str(ls[k]) for k in ("product", "category", "service") if ls.get(k)]
    return " / ".join(parts) or "n/a"


def load_rules() -> list[dict]:
    rules = []
    for path in sorted(RULES_DIR.glob("*.yml")):
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
        tags = [str(t) for t in raw.get("tags", [])]
        technique = ""
        for tag in tags:
            m = _TECH_RE.match(tag)
            if m:
                technique = m.group(1).upper() + (f".{m.group(2)}" if m.group(2) else "")
        tactics = [
            t.removeprefix("attack.").replace("_", " ").title().replace(" And ", " and ")
            for t in tags
            if t.startswith("attack.") and not _TECH_RE.match(t)
        ]
        condition = str(raw["detection"].get("condition", ""))
        rules.append({
            "file": path.name,
            "title": str(raw["title"]),
            "technique": technique,
            "tactics": tactics,
            "level": str(raw.get("level", "")),
            "logsource": _logsource(raw.get("logsource", {})),
            "kind": "threshold (count)" if "count()" in condition else "single event",
            "fixture": (FIXTURES_DIR / (path.stem + ".json")).exists(),
            "fp_count": len(raw.get("falsepositives", [])),
        })
    rules.sort(key=lambda r: (_SEVERITY_ORDER.get(r["level"], 9), r["technique"]))
    return rules


def _technique_link(tech: str) -> str:
    if not tech:
        return "n/a"
    return f"[{tech}](https://attack.mitre.org/techniques/{tech.replace('.', '/')}/)"


def render_table(rules: list[dict]) -> str:
    lines = [
        "| ATT&CK | Tactic(s) | Detection | Severity | Log source | Type | Attack fixture |",
        "|--------|-----------|-----------|----------|------------|------|:--------------:|",
    ]
    for r in rules:
        lines.append(
            f"| {_technique_link(r['technique'])} | {', '.join(r['tactics'])} "
            f"| [{r['title']}](../rules/sigma/{r['file']}) | {r['level']} | `{r['logsource']}` "
            f"| {r['kind']} | {'yes' if r['fixture'] else '**missing**'} |"
        )
    return "\n".join(lines)


def render_summary(rules: list[dict]) -> str:
    techniques = {r["technique"] for r in rules if r["technique"]}
    tactics = {t for r in rules for t in r["tactics"]}
    return (f"**{len(rules)} Sigma rules** covering **{len(techniques)} ATT&CK techniques** "
            f"across **{len(tactics)} tactics**.")


def render_catalogue(rules: list[dict]) -> str:
    return (
        "# Rule catalogue\n\n"
        "> Generated by `python pipeline/rule_catalogue.py` from the files in "
        "[`rules/sigma/`](../rules/sigma). Do not edit by hand; CI fails if it is stale.\n\n"
        f"{render_summary(rules)}\n\n"
        f"{render_table(rules)}\n\n"
        "Sorted by severity, then technique. *Type* is derived from the rule condition: "
        "threshold rules use a `count() by <field> >= N` aggregation (evaluated by the in-memory "
        "matcher, not expressible as a stateless Lucene query). *Attack fixture* means a "
        "true-positive log file exists under `tests/fixtures/sample_logs_malicious/`; whether the "
        "rule actually fires on it, and stays silent on the clean baseline, is decided by the test "
        "suite (see the CI badge), not by this table. Per-rule scope and known gaps: "
        "[mitre_attack/coverage_map.md](../mitre_attack/coverage_map.md).\n"
    )


def render_readme_block(rules: list[dict]) -> str:
    # README lives at the repo root, so rewrite the ../ links used in docs/.
    table = render_table(rules).replace("](../", "](")
    return f"{START}\n{render_summary(rules)}\n\n{table}\n{END}"


def updated_readme(text: str, rules: list[dict]) -> str:
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(text):
        raise SystemExit(f"README.md is missing the {START} ... {END} markers")
    return pattern.sub(lambda _: render_readme_block(rules), text)


def stale_files(rules: list[dict] | None = None) -> list[str]:
    """Names of generated files that no longer match the rules (empty = up to date)."""
    rules = rules if rules is not None else load_rules()
    stale = []
    if not CATALOGUE.exists() or CATALOGUE.read_text(encoding="utf-8") != render_catalogue(rules):
        stale.append(str(CATALOGUE.relative_to(ROOT)))
    readme = README.read_text(encoding="utf-8")
    if readme != updated_readme(readme, rules):
        stale.append("README.md")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    rules = load_rules()
    if args.check:
        stale = stale_files(rules)
        if stale:
            print("Stale generated file(s): " + ", ".join(stale))
            print("Run: python pipeline/rule_catalogue.py")
            return 1
        print("Rule catalogue is up to date.")
        return 0

    CATALOGUE.write_bytes(render_catalogue(rules).encode("utf-8"))
    readme = updated_readme(README.read_text(encoding="utf-8"), rules)
    README.write_bytes(readme.encode("utf-8"))
    print(f"Wrote {CATALOGUE.relative_to(ROOT)} and refreshed README table ({len(rules)} rules).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
